struct dkerror tmt_errs[] = {
	{0x01,	"Bus Timeout"},
	{0x02,	"Reverse at Begining of the Tape"},
	{0x03,	"End of the Tape"},
	{0x04,	"Unexpected File Mark"},
	{0x05,	"Formatter Busy"},
	{0x06,	"Tape Hard Error"},
	{0x07,	"Invalid Tape Address"},
	{0x08,	"Invalid Bus Width"},
	{0x09,	"Invalid Byte Count"},
	{0x0a,	"Invalid Command"},
	{0x0b,	"Invalid Count"},
	{0x0c,	"Invalid Retry Count"},
	{0x0d,	"Invalid Throttle Number"},
	{0x0e,	"Read Larger than Requested"},
	{0x0f,	"Link Parameter Block Error"},
	{0x10,	"Tape Not On Line"},
	{0x11,	"Parity Error"},
	{0x12,	"Read Over Run"},
	{0x13,	"Reverse to BOT"},
	{0x14,	"Read Smaller than Requested"},
	{0x15,	"Tape Soft Error"},
	{0x16,	"Tape is Write Protected"},
	{0x17,	"Tape Drive is Busy"},
	{0x18,	"Tape Not on Line"},
	{0x19,	"Tape Not Ready"},
	{0x1a,	"File Mark Not Detected"},
	{0x1b,	"Write Under Run"},
	{0x1c,	"Invalid Signals"},
	{0x1d,	"Blank Tape"},
	{0x1e,	"No Go Signal"},
	{0x1f,	"Invalid Block Length"},
	{0x20,	"Invalid Block Byte Count"},
	{0x21,	"Timeout: Data Busy never active"},
	{0x22,	"Timeout: Data Busy never inactive"},
	{0x23,	"No Write Strobe"},
	{0x24,	"Insufficent Number of Buffers"},
};
short tmt_nerrs = (sizeof(tmt_errs) / sizeof(struct dkerror));

#ifdef OS_DEBUG
struct	dkerror tmt_cmds[] = {
	{0x00,	"configure"},
	{0x01,	"read configuration"},
	{0x10,	"reset controller"},
	{0x11,	"rewind"},
	{0x12,	"secondary erase"},
	{0x13,	"erase the tape"},
	{0x14,	"on-line"},
	{0x15,	"off-line"},
	{0x16,	"variable erase"},
	{0x17,	"read tape status"},
	{0x18,	"variable erase to EOT"},
	{0x20,	"write file mark"},
	{0x21,	"search for file mark"},
	{0x22,	"space tape records"},
	{0x30,	"read the tape"},
	{0x31,	"ring buffer read"},
	{0x32,	"write the tape"},
	{0x33,	"ring buffer write"},
	{0x35,	"ring buffer write unlimited size"},
	{0x36,	"ring buffer read unlimited size"},
};
short tmt_ncmds = (sizeof(tmt_cmds) / sizeof(struct dkerror));
#endif
