# transcript/etc/Makefile
#
# Copyright 1985 Adobe Systems Incorporated
#
# RCSID: $Header: /d2/3.7/src/usr.bin/print/trscript/etc/RCS/Makefile,v 1.1 89/03/27 18:18:20 root Exp $
# RCSLOG:
# $Log:	Makefile,v $
# Revision 1.1  89/03/27  18:18:20  root
# Initial check-in for 3.7
# 
Revision 1.1  86/11/17  20:05:43  root
Initial revision

# Revision 2.1  85/11/24  12:28:42  shore
# Product Release 2.0
# 

nothing programs install:

clean:
	rm -f - *CKP *BAK .emacs_[0-9]*
