'\"macro stdmacro
.ds P UNIX
.TH IOCTL 2 
.SH NAME
ioctl \- control device
.SH SYNOPSIS
.B ioctl (fildes, request, arg)
.SH DESCRIPTION
.I Ioctl\^
performs a variety of functions
on character special files (devices).
The writeups of various devices
in Section 7 discuss how
.I ioctl\^
applies to them.
.PP
.I Ioctl\^
will fail if one or more of the following are true:
.RS .3i
.PP
.I Fildes\^
is not a valid open file descriptor.
.SM
\%[EBADF]
.PP
.I Fildes\^
is not associated with a character special device.
.SM
\%[ENOTTY]
.PP
.I Request\^
or
.I arg\^
is not valid.
See Section 7.
.SM
\%[EINVAL]
.RE
.SH RETURN VALUE
If an error has occurred,
a value of \-1 is returned and
.I errno\^
is set to indicate the error.
.SH "SEE ALSO"
termio(7) in the
.IR "\*P Programmer's Manual" .
.SH ASSEMBLER
.ta \w'\f3moveq\f1\ \ \ 'u 1.5i
.nf
.B moveq	#54,D0	| sys ioctl
.B movl	fildes,A0
.B movl	request,D1
.B movl	#argp,A1
.B trap	#0
.DT
.\"	@(#)ioctl.2	5.2 of 3/26/84
