.TH IRISDEMO
.SH NAME
irisdemo \- an animated presentation touting the IRIS
.SH SYNOPSIS
.B /usr/people/demos/irisdemo            
.SH DESCRIPTION
.I Irisdemo
is an animated presentation announcing our product line, and touting
the geometric, networking, and graphics features of the IRIS.
.PP
Pushing the right mouse button advances script through a set of pause points.
Holding the left button stops all action, and holding the middle button 
overrides the pause points.
This allows an announcer
to synchronize his talk with the
.I irisdemo
script.    
