.TH TPON 1
.SH NAME
tpon \- turn on the console textport
.SH SYNOPSIS
.B tpon
.SH DESCRIPTION
.PP
.I Tpon\^
allows the textport to be updated by non-graphics programs and when graphics
programs exit.
It is useful for re-enabling the textport after invoking
.IR tpblank .
.SH "SEE ALSO"
reshape(1), tpblank(1)
.\" @(#)$Header: /d2/3.7/src/man/trash/standard/u_man/man1/RCS/tpon.1,v 1.1 89/03/27 16:41:41 root Exp $
.\" $Log:	tpon.1,v $
Revision 1.1  89/03/27  16:41:41  root
Initial check-in for 3.7

.\" Revision 1.1  84/12/11  13:38:21  bob
.\" Initial revision
.\" 
