all:
	cd imglib; make
	cd portlib; make
	cd imgtools; make
	cd tools; make

clean:
	cd imglib; make clean
	cd portlib; make clean
	cd imgtools; make clean
	cd tools; make clean

install: 
	cd imglib; make install
	cd portlib; make install
	cd imgtools; make install
	cd tools; make install
