#
# swapfs_dd is made by scripts in /etc
#

install all:
	cd crt ; make $@
	cd mdfex; make $@
	cd ipfex; make $@
	cd memtest ; make $@

clean:
	cd crt ; make $@
	cd mdfexd ; make $@
	cd ipfexd ; make $@
	cd ipfex; make $@
	cd memtest ; make clobber
