# build all of Sendmail for the IRIS
#
# "$Header: /d2/3.7/src/bsd/usr.lib/sendmail/RCS/Makefile,v 1.1 89/03/27 15:02:30 root Exp $"


include ${ROOT}/usr/include/make/commondefs

default all install clean clobber:
	cd src; make $@
