MAKEFILE = Makefile
HDRS = \
	IrisConf.h \
	Qdevices.h \
	Qglobals.h \
	Qtypes.h \
	Xns.h \
	betacodes.h \
	betascreen.h \
	common.h \
	dbg.h \
	duart.h \
	i488.h \
	irisboot.h \
	iriskeybd.h \
	kbd.h \
	m68vectors.h \
	mem.h \
	ndbg.h \
	net.h \
	pm2.1.h \
	pmII.h \
	pmIImacros.h \
	remprom.h \
	ringbufs.h \
	setjmp.h

all:
	:
clean:
	:

release snapshot:
	$@ $(SRCS) $(HDRS) $(MAKEFILE)
