#ident	"$Header: /d2/3.7/src/sun/usr.lib/rpcsvc/RCS/Makefile,v 1.1 89/03/27 17:25:18 root Exp $"

include	../commondefs

LIBNAME= ../librpcsvc.a
PLIBNAME= ../librpcsvc_p.a
.PRECIOUS: $(LIBNAME) $(PLIBNAME)

CFILES= etherxdr.c mountxdr.c  rstatxdr.c rusersxdr.c rwallxdr.c sprayxdr.c \
	util.c yppwxdr.c

include ../commonrules
