#include "gl2cmds.h"

static parsefdback();

/* fbcname 2d shorts, 3d shorts, function */
static Feedbacktable feedbacktable[] = {
/*0*/ {"FBCinitfbc",	 	 0, 0,	parsefdback},
/*1*/ {0,		 	 0, 0,  parsefdback},
/*2*/ {"FBCmasklist",		-1,-1,	parsefdback},
/*3*/ {"GEstoremm",			32,32,	parsefdback},
/*4*/ {"FBCrgbcolor",	 	 3, 3,	parsefdback},
/*5*/ {"FBCrgbwrten",	 	 3, 3,	parsefdback},
/*6*/ {"FBCsethitmode",		 0, 0,	parsefdback},
/*7*/ {"FBCclearhitmode",	 0, 0,	parsefdback},
/*8*/ {"FBCforcecompletion",	 0, 0,	parsefdback},
/*9*/ {"FBCbaseaddress",	 1, 1,	parsefdback},
/*10*/{"FBCcdcolorwe",	 	 2, 2,	parsefdback},
/*11*/{"GEstoreviewport",	12,12,	parsefdback},
/*12*/{"GEreconfigure",	 	 0, 0,	parsefdback},
/*13*/{"FBCdrawpixels",		-1,-1,	parsefdback},
/*14*/{"FBCreadpixels",		 1, 1,	parsefdback},
/*15*/{"GEnoop",	 	 0, 0,	parsefdback},
/*16*/{"FBCmove",		 2, 4,	parsefdback},
/*17*/{"FBCdraw",		 2, 4,	parsefdback},
/*18*/{"FBCpoint",		 2, 4,	parsefdback},
/*19*/{"GEcurve",	 	 0, 0,	parsefdback},
/*20*/{"FBCcolor",		 1, 1,	parsefdback},
/*21*/{"FBCwrten",		 1, 1,	parsefdback},
/*22*/{"FBCconfig",		 2, 2,	parsefdback},
/*23*/{"FBCloadmasks",		-1,-1,	parsefdback},
/*24*/{"FBCselectrgbcursor",	 9, 9,	parsefdback},
/*25*/{"FBClinewidth",	 	 1, 1,	parsefdback},
/*26*/{"FBCcharposnabs",	 3, 5,	parsefdback},
/*27*/{"FBCcharposnrel",	 3, 5,	parsefdback},
/*28*/{"FBCdrawchars",		-1,-1,	parsefdback},
/*29*/{"FBCselectcursor",	 7, 7,	parsefdback},
/*30*/{"FBCdrawcursor",		 2, 2,	parsefdback},
/*31*/{"FBCundrawcursor",	 0, 0,	parsefdback},
/*32*/{"FBClinestipple",	 2, 2,	parsefdback},
/*33*/{"FBCpolystipple",	 1, 1,	parsefdback},
/*34*/{"FBCsaveregs",		-1,-1,	parsefdback},
/*35*/{"FBCunsaveregs",		-1,-1,	parsefdback},
/*36*/{"FBCdepthsetup",		 6, 6,	parsefdback},
/*37*/{"FBCfeedback",		 0, 0,	parsefdback},
/*38*/{"FBCeof",		 1, 1,	parsefdback},
/*39*/{"FBCreadcharposn",	 0, 0,	parsefdback},
/*40*/{"FBCcopyfont",		 3, 3,	parsefdback},
/*41*/{"FBCpushname",		 1, 1,	parsefdback},
/*42*/{"FBCloadname",		 1, 1,	parsefdback},
/*43*/{"FBCpopname",		 0, 0,	parsefdback},
/*44*/{"FBCfixharload",		 3, 3,	parsefdback},
/*45*/{"FBCfixchardraw",	 1, 1,	parsefdback},
/*46*/{"FBCinitnamestack",	 0, 0,	parsefdback},
/*47*/{"FBCpixelsetup",		 2, 2,	parsefdback},
/*48*/{"FBCmovepoly",		 2, 4,	parsefdback},
/*49*/{"FBCdrawpoly",		 2, 4,	parsefdback},
/*50*/{"FBCloadram",		-1,-1,	parsefdback},
/*51*/{"FBCclosepoly",		 0, 0,	parsefdback},
/*52*/{"FBCdrawmode",		 2, 2,	parsefdback},
/*53*/{"FBCsetintensity",	 1, 1,	parsefdback},
/*54*/{"FBCsetbackfacing",	 1, 1,	parsefdback},
/*55*/{"BPCreadbus",		-1,-1,	parsefdback},
/*56*/{"FBCxformpt",		 8, 8,	parsefdback},
/*57*/{"FBCblockfill",		 4, 4,	parsefdback},
/*58*/{"FBCdumpram",		-1,-1,	parsefdback},
/*59*/{"FBCzshadescanline",	10,10,	parsefdback},
/*60*/{"BPCcommand",		-1,-1,	parsefdback},
/*61*/{"FBCcopyscreen",		 5, 5,	parsefdback},
/*62*/{"FBCinitscanline",	 1, 1,	parsefdback}
};
#define TABLE_END 63
