# makefile for making BSD libraries
# $Source: /d2/3.7/src/bsd/usr.lib/RCS/Makefile,v $
# @(#)$Revision: 1.1 $
# $Date: 89/03/27 15:00:53 $

all install clean clobber:
	cd libbsd	; make $@
	cd libdbm	; make $@
	cd sendmail	; make $@

boot:
	cd libbsd	; make $@
	cd libdbm	; make $@
