# $Source: /d2/3.7/src/man/a_man/RCS/Makefile,v $
# @(#)$Revision: 1.1 $
# $Date: 89/03/27 16:19:49 $

all install clean clobber:
	cd man1			; make $@
	cd man7			; make $@
	cd man8			; make $@

man1:	FRC
	cd man1			; make all

man7:	FRC
	cd man7			; make all

man8:	FRC
	cd man8			; make all

FRC:
