#ident	"$Header: /d2/3.7/src/sun/usr.lib/net/RCS/Makefile,v 1.1 89/03/27 17:24:09 root Exp $"

include	../commondefs

CFILES= ether_addr.c gethostent.c getnetent.c getnetgent.c getprotent.c \
	getrpcent.c getservent.c innetgr.c rcmd.c ruserpass.c

include ../commonrules
