_YVALUE	- zshadetrap
_I	- zshadetrap
_XRIGHT_HI	- zshadetrap
_DEL_HI	- zshadetrap
_XLEFT_HI	- zshadetrap
_Z_LEFT_HI_ZS	- zshadetrap
_Z_LEFT_LO_ZS	- zshadetrap
_DEL_LO	- zshadetrap
_Z_RIGHT_HI_ZS	- zshadetrap
_Z_RIGHT_LO_ZS	- zshadetrap
_COLOR_LEFT_LO	- zshadetrap
_COLOR_RIGHT_LO	- zshadetrap
_COLOR_LEFT_HI	- zshadetrap
_COLOR_RIGHT_HI	- zshadetrap
_I	- zshadeline
_Z_LEFT_LO_ZS	- zshadeline
_Z_LINE_LO_ZS	- zshadeline
_COLOR_LEFT_LO	- zshadeline
_COLOR_LINE_LO	- zshadeline
_Z_LEFT_HI_ZS	- zshadeline
_COLOR_LEFT_HI	- zshadeline
_XRIGHT_HI	- zshadeline
_XLEFT_HI	- zshadeline
_YVALUE	- zshadeline
_Z_LINE_HI	- zshadeline
_COLOR_LINE_HI	- zshadeline
_Z_LINE_HI	- fastzshadeline
_COLOR_LINE_HI	- fastzshadeline
_Z_LINE_LO	- fastzshadeline
_COLOR_LINE_LO	- fastzshadeline
_I	- fastzshadeline
_YVALUE	- fastzshadeline
