/*
 *	Kurt Akeley
 *	4 August 1984
 *
 *	Command number definitions
 */

#define C_NOTACOMMAND	-1
#define C_BALL		0
#define C_BPCTEST	1
#define C_BPLAMPTEST	2
#define C_BPTEST	3
#define C_CHARTEST	4
#define C_CLEAR		5
#define C_CMNDLIST	6
#define C_COLORCODE	7
#define C_COLORWETEST	8
#define C_COLOR		9
#define C_DCLAMPTEST	10
#define C_DCRTEST	11
#define C_DCR		12
#define C_DISPLAY	13
#define C_DRAWCHAR	14
#define C_DRAWLINE	15
#define C_FILLRECT	16
#define C_FMTEST	17
#define C_INIT		18
#define C_JOESCALE	19
#define C_LDCONFIG	20
#define C_LDEC		21
#define C_LDED		22
#define C_LDFMADDR	23
#define C_LDXE		24
#define C_LDXS		25
#define C_LDYE		26
#define C_LDYS		27
#define C_LINETEST	28
#define C_LOOPCLEARWORD	29
#define C_LOOP		30
#define C_MAPCOLOR	31
#define C_MAPTEST	32
#define C_MEMTEST	33
#define C_QUIT		34
#define C_RAMPTEST	35
#define C_RANDLINES	36
#define C_RANDRECT	37
#define C_READFM	38
#define C_READLOOP	39
#define C_READMAP	40
#define C_READWORD	41
#define C_READ		42
#define C_RECTTEST	43
#define C_REQUEST	44
#define C_RGBCOLOR	45
#define C_ROTATELOOP	46
#define C_SCREENMASK	47
#define C_SCRMSKTEST	48
#define C_SIGPLANES	49
#define C_STEPTEST	50
#define C_STRIPETEST	51
#define C_STRIPE	52
#define C_SWAP		53
#define C_UCLAMPTEST	54
#define C_WECODE	55
#define C_WE		56
#define C_WRITEMAP	57
#define C_WRITELOOP	58
#define C_WRITEWORD	59
#define C_WRITE		60
#define C_NEWARG	61
#define C_DCPAL		62
#define C_SCROLL	63
#define C_DEFMACRO	64
#define C_EDITMACRO	65
#define C_ENDMACRO	66
#define C_MACRO		67
#define C_LDMODE	68
#define C_LDREPEAT	69
#define C_LDDDASAF	70
#define C_LDDDASAI	71
#define C_LDDDASDF	72
#define C_LDDDASDI	73
#define C_LDDDAEAF	74
#define C_LDDDAEAI	75
#define C_LDDDAEDF	76
#define C_LDDDAEDI	77
#define C_UCR		78
#define C_FILLTRAP	79
#define C_DEPTHCUE	80
#define C_READDDA	81
#define C_TIME		82
#define C_SEEMACRO	83
#define C_DDATEST	84
#define C_PIXELTEST	85
#define C_REVISION	86
#define C_HELP		87
#define C_HISTORY	88
#define C_TRAPTEST	89
#define C_SAVE		90
#define C_RESTORE	91
#define C_WRITEFM	92
#define C_GFTEST	93
#define C_PRINT		94
#define C_FPTEST	95
