#ident	"$Header: /d2/3.7/src/sun/usr.lib/rpc/RCS/Makefile,v 1.1 89/03/27 17:24:22 root Exp $"

include	../commondefs

CFILES= auth_none.c auth_unix.c authu_prot.c \
	clnt_perr.c clnt_raw.c clnt_simp.c clnt_tcp.c clnt_udp.c \
	pmap_clnt.c pmap_gmaps.c pmap_gport.c pmap_prot.c pmap_rmt.c \
	rpc_prot.c svc.c svc_auth.c svc_auth_u.c \
	svc_raw.c svc_simp.c svc_tcp.c svc_udp.c \
	xdr.c xdr_array.c xdr_float.c xdr_mem.c xdr_rec.c xdr_refer.c \
	xdr_stdio.c

include ../commonrules
