#ident	"$Header: /d2/3.7/src/sun/usr.lib/yp/RCS/Makefile,v 1.1 89/03/27 17:25:42 root Exp $"

include	../commondefs

CFILES= yp_all.c yp_bind.c yp_enum.c yp_master.c yp_match.c yp_order.c \
	yperrstr.c ypprot_err.c ypv1_xdr.c ypxdr.c

include ../commonrules
