'\"macro stdmacro
.TH ETHERS 4
.SH NAME
ethers \- ethernet address to hostname database
.SH SYNOPSIS
.B /etc/ethers
.SH DESCRIPTION
The
.I ethers
file contains information regarding the 
known (48 bit) ethernet addresses of hosts on the internet.
For each host on an ethernet,
a single line should be present with the following information:
.LP
	ethernet address
.br
	official host name
.LP
Items are separated by any number of blanks and/or tabs.
A `#' indicates the beginning of a comment
extending to the end of line.
.LP
The standard form for ethernet addresses is ``x:x:x:x:x:x'' where
.I x
is a hexadecimal number between 0 and ff, representing one byte.
The address bytes are always in network order.
Host names may contain any printable character other than
a space, tab, newline, or comment character.
It is intended that host names in the
.I ethers
file correspond to the host names in the
.IR hosts (4)
file.
.LP
The
.IR ether_line ()
routine from the ethernet address manipulation library,
.IR ethers (3R)
may be used to scan lines of the
.I ethers
file.
.SH FILES
/etc/ethers
.SH "SEE ALSO"
ethers(3R), hosts(4)
