'\"macro stdmacro
.TH FSPEC 4
.SH NAME
fspec \- format specification in text files
.SH DESCRIPTION
It is sometimes convenient to
maintain text files on the \s-1UNIX\s0 System
with non-standard tabs,
(i.e.,
tabs which are not set at every eighth column).
Such files must generally be converted
to a standard format,
frequently by replacing all tabs with
the appropriate number of spaces,
before they can be processed by \s-1UNIX\s0 System commands.
A format specification
occurring in the first line of a text file
specifies how tabs are to be expanded in the remainder of the file.
.PP
A format specification consists of a sequence of parameters
separated by blanks and surrounded by the brackets
\f3<:\fP and \f3:>\fP.
Each parameter consists of a keyletter,
possibly followed immediately by a value.
The following parameters are recognized:
.PP
.TP 9
\f3t\f2tabs\f1
The
.B t
parameter specifies
the tab settings for the file.
The value of
.I tabs\^
must be one of the following:
.RS 9
.PD 0
.IP "1." 3
a list of column numbers separated by commas,
indicating tabs set at the specified columns;
.IP "2." 3
a \f3\-\fP followed immediately by an integer
.IR n ,
indicating tabs at intervals of
.I n\^
columns;
.IP "3." 3
a \f3\-\fP followed by the name of a ``canned'' tab specification.
.RE
.PD
.TP 9
\&
Standard tabs are specified by \f3t \- 8\fP, or equivalently,
.BR t1,9,17,25, etc.
The canned tabs which are recognized are defined by the
.IR tabs (1)
command.
.TP 9
\f3s\f2size\f1
The
.B s
parameter specifies a maximum line size.
The value of
.I size\^
must be an integer.
Size checking is performed after tabs have been expanded,
but before the margin is prepended.
.TP 9
\f3m\f2margin\f1
The
.B m
parameter specifies a number of spaces to be
prepended to each line.
The value of
.I margin\^
must be an integer.
.TP 9
\f3d\f1
The
.B d
parameter takes no value.
Its presence indicates that the line containing the format specification
is to be deleted from the converted file.
.TP 9
\f3e\f1
The
.B e
parameter takes no value.
Its presence indicates that the current format is to prevail
only until another format specification
is encountered in the file.
.PP
Default values, which are assumed for parameters not supplied,
are \f3t \- 8\fP and \f3m0\fP.
If the
.B s
parameter is not specified, no size checking is performed.
If the first line of a file does not contain a format specification,
the above defaults are assumed for the entire file.
The following is an example of a line containing a format specification:
.PP
.RS
\(** <:t5,10,15 s72:> \(**
.RE
.PP
If a format specification can be disguised as a comment,
it is not necessary to code the
.B d
parameter.
.PP
Several
.SM UNIX
System commands correctly interpret the format specification for a file.
Among them is
.I gath\^
which
may be used to convert files to a standard format
acceptable to other \s-1UNIX\s0 System commands.
.SH SEE ALSO
ed(1), newform(1), tabs(1).
.\"	@(#)fspec.4	5.1 of 10/23/83
