'\"macro stdmacro
.ds P UNIX
.TH INTRO 4
.SH NAME
intro \- introduction to file formats
.SH DESCRIPTION
This section outlines the formats of various files.
The C
.B struct
declarations for the file formats are given where applicable.
Usually, these structures can be found in the
directories
.B /usr/include
or
.BR /usr/include/sys .
.PP
References of the type
.IR name (sect)
refer to entries found in Section 
.I sect
of the
.IR "\*P Programmer's Manual" .
.\"	@(#)intro.4	5.1 of 10/17/83
