'\"macro stdmacro
.TH PNCH 4
.SH NAME
pnch \- file format for card images
.SH DESCRIPTION
The \s-1PNCH\s0 format is a convenient representation for
files consisting of card images in an arbitrary code.
.PP
A \s-1PNCH\s0 file is a simple concatenation of card records.
A card record consists of a single control byte followed
by a variable number of data bytes.
The control byte specifies the number
(which must lie in the range 0-80) of data bytes that
follow.
The data bytes are 8-bit codes that constitute
the card image.
If there are fewer than 80 data bytes, it is understood
that the remainder of the card image consists of trailing
blanks.
.\"	@(#)pnch.4	5.1 of 10/15/83
