#	libplot make file
#	SCCS:	@(#)libplot.mk	1.2

all install clean clobber:
	cd plot		; make $@
	cd t300		; make $@
	cd t300s	; make $@
	cd t4014	; make $@
	cd t450		; make $@
	cd vt0		; make $@

plot:	FRC
	cd $@ ; make all

t300:	FRC
	cd $@ ; make all

t300s:	FRC
	cd $@ ; make all

t4014:	FRC
	cd $@ ; make all

t450:	FRC
	cd $@ ; make all

vt0:	FRC
	cd $@ ; make all

FRC:
