'\"macro stdmacro
.TH PSREV 1
.SH NAME
psrev \- select or reverse page order of a P\s-2OST\s+2S\s-2CRIPT\s+2 file
.SH SYNOPSIS
.B psrev
[ 
.B \-R
] [
.BR \-s pagespec
] [ file ]
.SH DESCRIPTION
.I psrev
reads in a P\s-2OST\s+2S\s-2CRIPT\s+2 
.I file
(or the standard input if no file is named), and if the
input conforms to the P\s-2OST\s+2S\s-2CRIPT\s+2 file structuring conventions,
reverses and selects the specified pages for printing
and writes the resulting file  on the standard output.
.sp
The possible options are:
.TP
.BI \-s " pagespec"
specifies a range (or several ranges) of pages to be printed.
.I Pagespec
is a string, not containing spaces, of the form ``pagerange[,pagespec]''.
.I Pagerange
may be a single page number or a range 
of the form ``N-M'' which means print pages N through M.
-N means print from the beginning of the document to page N.  
M- means print from page M to the end of the document.
.TP
.B \-R
does not reverse the page order, (but subset the pages if specified).
.SH FILES
.TP 2.2i
/usr/tmp/RV*
temporary file if input is a pipe.
.br
.SH "SEE ALSO"
enscript(1), postscript(4).
.SH "DIAGNOSTICS"
Should be self explanatory.
.SH AUTHOR
Adobe Systems Incorporated
.SH "NOTES"
P\s-2OST\s+2S\s-2CRIPT\s+2 is a trademark of Adobe Systems Incorporated.
