# @(#)$Header: /d2/3.7/src/man/gl1/u_man/man3/RCS/Makefile,v 1.1 89/03/27 16:33:11 root Exp $
# $Log:	Makefile,v $
# Revision 1.1  89/03/27  16:33:11  root
# Initial check-in for 3.7
# 
# Revision 1.1  89/03/27  16:35:45  root
# Initial check-in for 3.7
# 

M	= u
S	= 3

all clean clobber:

install:
	cp *.$Sg $(DEST)/usr/man/$M_man/man$S
	cd $(DEST)/usr/man/$M_man/man$S;chmod 644 *.$Sg
	cd $(DEST)/usr/man/$M_man/man$S;chgrp bin *.$Sg;chown bin *.$Sg

FRC:
