'\"macro stdmacro
.TH AUTOROBOTS 6
.SH NAME
autorobots \- escape from the automatic robots
.SH SYNOPSIS
.B /usr/games/autorobots
.SH DESCRIPTION
.PP
The object of the game
.I autorobots
is to move around inside of the box
on the screen
without getting eaten by the robots chasing you
and without running into any robots or junk heaps.
The robots move continuously.
.PP
If a robot runs into another robot or junk heap while chasing you,
they crash and leave a junk heap.
.PP
You start out with 10 robots worth 10 points each.
If you defeat all of them,
you get 20 robots worth 20 points each.
Then 30, etc.
Until you get eaten!
.PP
The game keeps track of the top ten scores
and prints them at the end of the game.
.PP
The valid commands are described on the screen.
.\"	@(#)autorobots.6	5.1 of 10/18/83
