'\"macro stdmacro
.TH RAIN 6 
.SH NAME
rain \- animated raindrops display
.SH SYNOPSIS
rain
.SH DESCRIPTION
.PP
.ad b
.IR Rain 's
display is modeled after the 
.SM VAX/VMS
program of the same name.
The terminal has to be set for 9600 baud to
obtain the proper effect.
.PP
As with all programs that use
.IR termcap ,
the 
.SM TERM
environment variable must be set (and exported) to the 
type of the terminal being used.
.SH FILES
/etc/termcap
.SH AUTHOR
Eric P. Scott
.\"	@(#)rain.6	5.1 of 10/18/83
