#include "opt.h"

/* added jbsr recognition GB (SGI) 8/20/83 */
struct optab optab[] = {
	"bra",	JBR,
	"beq",	CBR | JEQ<<8,
	"bne",	CBR | JNE<<8,
	"ble",	CBR | JLE<<8,
	"bge",	CBR | JGE<<8,
	"blt",	CBR | JLT<<8,
	"bgt",	CBR | JGT<<8,
	"bcs",	CBR | JLO<<8,
	"bhi",	CBR | JHI<<8,
	"bls",	CBR | JLOS<<8,
	"bcc",	CBR | JHIS<<8,

	"jra",	XFER | JRA<<8,
	"jeq",	XFER | JEQ<<8,
	"jne",	XFER | JNE<<8,
	"jle",	XFER | JLE<<8,
	"jge",	XFER | JGE<<8,
	"jlt",	XFER | JLT<<8,
	"jgt",	XFER | JGT<<8,
	"jcs",	XFER | JLO<<8,
	"jhi",	XFER | JHI<<8,
	"jls",	XFER | JLOS<<8,
	"jcc",	XFER | JHIS<<8,

	"dbra",	DB | JRA<<8,

	"jmp",	JMP,
	".globl",EROU,
	".word",JSW,
	"mov",	MOV,
	"clr",	CLR,
	"not",	NOT,
	"addq",	ADDQ,
	"subq",	SUBQ,
	"neg",	NEG,
	"tst",	TST,
	"asr",	ASR,
	"asl",	ASL,
	"lsr",	LSR,
	"lsl",	LSL,
	"ext",	EXT,
	"cmp",	CMP,
	"add",	ADD,
	"sub",	SUB,
	"and",	AND,
	"or",	OR,
	"eor",	EOR,
	"muls",	MULS,
	"mulu",	MULU,
	"divs",	DIVS,
	"divu",	DIVU,
	"jbsr", JSR,
	"jsr",	JSR,
	"bsr",	BSR,
	"lea",	LEA,
	"pea",	PEA,
	"btst",	BTST,
	"movem",MOVEM,
	"moveq",MOVEQ,
	"link",	LINK,
	"unlk",	UNLK,
	"swap", SWAP,
	"ror", ROR,
	"cmpm", CMPM,
	".text",TEXT,
	".data",DATA,
	".bss",	BSS,
	".even",EVEN,
	".end",	END,
	0,	0
};
