FUNCTION $asin(arg:REAL) : REAL;EXTERNAL;

FUNCTION $acos(arg:REAL) : REAL;EXTERNAL;

FUNCTION $atan2(y,x:REAL) : REAL;EXTERNAL;

FUNCTION $sinh(arg:REAL) : REAL;EXTERNAL;

FUNCTION $cosh(arg:REAL) : REAL;EXTERNAL;

FUNCTION $tanh(arg:REAL) : REAL;EXTERNAL;

FUNCTION $pow(base,power:REAL) : REAL;EXTERNAL;

FUNCTION $up_i(base:REAL; pow:LONGINT) : REAL;EXTERNAL;

