
include ${ROOT}/usr/include/make/commondefs

all clean clobber:
	cd examples ; make $@
	cd kermit; make $@
	cd gl_tutor; make $@
	cd fgl_tutor; make $@


install:
	cd examples; make $@
	cd dbx_tutorial; make $@
	cd kermit; make $@
	cd gl_tutor; make $@
	cd fgl_tutor; make $@
