# $Source: 
# @(#)$Revision:
# $Date:

all install clean clobber:
	cd man1			; make $@
	cd man4			; make $@
	cd man5			; make $@

man1:	FRC
	cd man1			; make $@

man4:	FRC
	cd man4			; make $@

man5:	FRC
	cd man5			; make $@

FRC:
