'\"macro stdmacro
.TH BANNER 1
.SH NAME
banner \- make posters
.SH SYNOPSIS
.B banner
strings
.SH DESCRIPTION
.I Banner\^
prints its arguments (each up to 10 characters long)
in large letters on the standard output.
.SH EXAMPLE
.IP
banner asa
.PP
will cause the characters "a", "s" and "a" to be printed as large
letters on the screen.
.SH SEE ALSO
echo(1).
.\"	@(#)banner.1	5.1 of 10/26/83
