'\"macro stdmacro
.\".if t .ds ' \h@.05m@\s+4\v@.333m@\'\v@-.333m@\s-4\h@.05m@
.if t .ds ' '
.if n .ds ' '
.\".if t .ds ` \h@.05m@\s+4\v@.333m@\`\v@-.333m@\s-4\h@.05m@
.if t .ds ` `
.if n .ds ` `
.TH BASENAME 1
.SH NAME
basename, dirname \- deliver portions of path names
.SH SYNOPSIS
.B basename
string [ suffix ]
.br
.B dirname
string
.SH DESCRIPTION
.I Basename\^
deletes any prefix ending in
.B /
and the
.I suffix\^
(if present in
.IR string\^ )
from
.IR string ,
and prints the result on the standard output.
It is normally used inside substitution marks
.RB ( \^`\0`\^ )
within shell procedures.
.PP
.I Dirname\^
delivers all but the last level of the path name in
.IR string .
.SH EXAMPLE
Invoked with the argument
.BR /usr/src/cmd/cat.c ,
.IP
cc \|$1
.br
mv \|a.out \|`basename \|$1 \|.c`
.PP
compiles the named file and moves the output to
a file named
"cat"
in the current directory.
.IP
\s-1NAME\s+1=`dirname \|/usr/src/cmd/cat.c`
.PP
sets the shell variable
.SM
.B NAME
to
.BR /usr/src/cmd .
.SH SEE ALSO
sh(1).
.SH BUGS
The
.I basename\^
of
.B /
is null and
is considered an error.
.\"	@(#)basename.1	5.1 of 11/17/83
