'\"macro stdmacro
.TH CD 1
.SH NAME
cd \- change working directory
.SH SYNOPSIS
.B cd
[ directory ]
.SH DESCRIPTION
If
.I directory\^
is not specified, the value of shell parameter
.B
.SM $HOME
is used as the new working directory.
If
.I directory\^
specifies a complete path starting with
.BR / ,
.BR \&. ,
.BR \&.\|. ,
.I directory\^
becomes the new working directory.
If neither case applies,
.I cd\^
tries to find the designated directory relative to one of the
paths specified by the
.B
.SM $CDPATH
(\f2sh\f1(1)) or 
.B
$cdpath
(\f2csh\f1(1)) shell variables.
.B
.SM $CDPATH
and 
.B
$cdpath
have the same syntax as, and similar semantics to, the
.B
.SM $PATH
and
.B
$path
shell variables.
.I cd\^
must have execute (search) permission in
.IR directory\^ .
.PP
Because a new process is created to execute each command,
.I cd\^
would be ineffective if it were written as a
normal command;
therefore, it is recognized and internal to
the shell.
.SH EXAMPLE
.IP
cd /usr/games 
.PP
would relocate you to the directory 
.B /usr/games
if this directory is 
executable (searchable) by you.
.SH SEE ALSO
csh(1), pwd(1), sh(1), chdir(2).
.\"	@(#)cd.1	5.1 of 10/26/83
