'\"macro stdmacro
.TH DBPRINT 1
.SH NAME
dbprint \- print a database entry
.SH SYNOPSIS
.PP
.B
dbprint
.I
database-name key
.SH DESCRIPTION
.PP
.I
Dbprint
prints the contents of the database with the given key.
For information on the 
Emacs
database facility, see the following documents:
.PP
.RS 5
.I
Emacs Reference Manual
.br
.SH SEE ALSO
Several utilities, in addition to dbprint,
are provided for manipulating the Emacs databases outside of Emacs.
.IP "dbcreate(1)" 17
create a database.
.IP "dbbuild(1)" 17
builds a database from a shell command file.
.IP "dblist(1)" 17
lists the keys in the database.
.IP "dbadd(1)" 17
adds an entry to a database.
