'\"macro stdmacro
.TH FSPLIT 1
.SH NAME
fsplit \- split fortran or ratfor files
.SH SYNOPSIS
.B fsplit
options files
.SH DESCRIPTION
.I Fsplit\^
splits the named 
.IR file\^ ( s )
into separate files, with one procedure per
file.
A procedure includes \f2blockdata\fP, \f2function\fP, \f2main\fP, \f2program\fP,
and \f2subroutine\fP program segments.
Procedure \f2X\fP is put in file
.I X\^ 
.BR .f ,
.I X\^ 
.BR .r ,
or
.IB X\^ .e
depending on the language
option chosen, with the following exceptions: \f2main\^\fP is put in the file
.IB MAIN .[efr]
and unnamed \f2blockdata\^\fP segments in the files
.IB blockdataN .[efr]
where \f2N\^\fP is a unique integer value for each file.
.PP
The following
.I options\^
pertain:
.TP "\w'\f3\-f\fP\ \ \ 'u"
.B \-f
(default) Input files are
.IR fortran .
.TP
.B \-r
Input files are
.IR ratfor .
.TP
.B \-s
Strip
.I fortran\^
input lines to 72 or fewer characters with trailing blanks
removed.
.SH SEE ALSO
csplit(1),
split(1).
.\"	@(#)fsplit.1	5.1 of 11/8/83
