'\"macro stdmacro
.TH IPCRM 1
.SH NAME
ipcrm \- remove a message queue, semaphore set or shared memory id
.SH SYNOPSIS
.B ipcrm
[ options ]
.SH DESCRIPTION
.I ipcrm\^
will remove one or more specified message, semaphore or shared
memory identifiers.  The identifiers are specified
by the following \f2options\f1:
.TP 12
\f3\-q\f2 msqid\f1
removes the message queue identifier \f2msqid\f1
from the system and destroys the message queue
and data structure associated with it.
.TP
\f3\-m\f2 shmid\f1
removes the shared memory identifier \f2shmid\f1
from the system.  The shared memory segment and data
structure associated with it are destroyed after
the last detach.
.TP
\f3\-s\f2 semid\f1
removes the semaphore identifier \f2semid\f1
from the system and destroys the set of semaphores and
data structure associated with it.
.TP 12
\f3\-Q\f2 msgkey\f1
removes the message queue identifier, created with key \f2msgkey\f1,
from the system and destroys the message queue
and data structure associated with it.
.TP
\f3\-M\f2 shmkey\f1
removes the shared memory identifier, created with key \f2shmkey\f1,
from the system.  The shared memory segment and data
structure associated with it are destroyed after
the last detach.
.TP
\f3\-S\f2 semkey\f1
removes the semaphore identifier, created with key \f2semkey\f1,
from the system and destroys the set of semaphores and
data structure associated with it.
.PP
The details of the removes are described in \f2msgctl\f1(2),
\f2shmctl\f1(2), and \f2semctl\f1(2).
The identifiers and keys may be found by using \f2ipcs\f1(1).
.SH "SEE ALSO"
.na
ipcs(1), msgctl(2), msgget(2), msgop(2), semctl(2), semget(2), semop(2),
shmctl(2), shmget(2), shmop(2).
.ad
.\"	@(#)ipcrm.1	5.2 of 5/18/82
