'\"macro stdmacro
.TH LINE 1
.SH NAME
line \- read one line
.SH SYNOPSIS
.B line
.SH DESCRIPTION
.I Line\^
copies one line (up to a new-line) from the standard
input and writes it on the standard output.
It
returns an exit code of 1 on
.SM
.B EOF
and always
prints at least a new-line.
It is often used within shell files to
read from the user's terminal.
.SH EXAMPLE
.IP
line
.br
Hello world
.PP
will return
.IP
Hello world
.PP
In the Bourne shell (sh):
.IP
a=`line`
.br
hi there
.br
echo $a
.PP
will return
.IP
hi there
.PP
In the C-shell (csh):
.IP
set a=`line`
.br
bye bye
.br
echo $a
.PP
will return
.IP
bye bye
.SH "SEE ALSO"
sh(1), read(2).
.\"	@(#)line.1	5.1 of 11/17/83
