'\"macro stdmacro
.TH M4 1
.SH NAME
m4 \- macro processor
.SH SYNOPSIS
.B m4
[ options ]
[ files ]
.SH DESCRIPTION
.I M4\^
is a macro processor
intended as a front end for Ratfor, C, and other languages.
Each of the argument files is processed in order;
if there are no files, or if a file name is
.BR \- ,
the standard input is read.
The processed text is written on the standard output.
.PP
The options and their effects are as follows:
.TP "\w'\f3\-H\|\f2int\f1\ \ 'u"
.B \-e
Operate interactively.
Interrupts are ignored and the output is unbuffered.
Using this mode requires a special state of mind.
.TP
.B \-s
Enable line sync output for the C preprocessor
.RB ( # "line .\|.\|.\|)"
.TP
.BI \-B\| int\^
Change the size of the push-back and argument collection
buffers from the default of 4,096.
.TP
.BI \-H\| int\^
Change the size of the symbol table hash array from the
default of 199.
The size should be prime.
.TP
.BI \-S\| int\^
Change the size of the call stack from the default of 100 slots.
Macros take three slots, and non-macro arguments take one.
.TP
.BI \-T\| int\^
Change the size of the token buffer from the default of 512 bytes.
.PP
To be effective, these flags must appear before any
file names and before any
.B \-D
or
.B \-U
flags:
.TP "\w'\f3\-H\|\f2int\f1\ \ 'u"
\f3\-D\|\f2name\^\f1[\f3=\f2val\^\f1]
Defines
.I name\^
to
.I val\^
or to null in
.IR val\^ 's
absence.
.TP
.BI \-U\| name
undefines
.IR name .
.PP
Macro calls
have the form:
.PP
.RS
name(arg1,arg2, .\|.\|., argn)
.RE
.PP
The
.B (
must immediately follow the name of the macro.
If the name of a defined macro is not followed by a
.BR ( ,
it is deemed to be a call of that macro with no arguments.
Potential macro names consist of alphabetic letters,
digits, and underscore
.BR \_\| ,
where the first character is not a digit.
.PP
Leading unquoted blanks, tabs,
and new-lines are ignored while collecting arguments.
Left and right single quotes are used to quote strings.
The value of a quoted string is the string stripped of the quotes.
.PP
When a macro name is recognized,
its arguments are collected by searching for a matching right
parenthesis.
If fewer arguments are supplied than are in the macro definition,
the trailing arguments are taken to be null.
Macro evaluation proceeds normally during the collection of the arguments,
and any commas or right parentheses
which happen to turn up within the value of a nested
call are as effective as those in the original input text.
After argument collection,
the value of the macro is pushed back onto the input stream
and rescanned.
.PP
.I M4\^
makes available the following built-in macros.
They may be redefined, but once this is done the original meaning is lost.
Their values are null unless otherwise stated.
.TP "\w'changequote\ \ 'u"
define
the second argument is installed as the value of the macro
whose name is the first argument.
Each occurrence of
.BI $ n\^
in the replacement text,
where
.I n\^
is a digit,
is replaced by the
.IR n -th
argument.
Argument 0 is the name of the macro;
missing arguments are replaced by the null string;
.BR $ #
is replaced by the number of arguments;
.BR $ \(**
is replaced by a list of all the arguments separated by commas;
.BR $ @
is like
.BR $ \(**,
but each argument is quoted (with the current quotes).
.TP
undefine
removes the definition of the macro named in its argument.
.TP
defn
returns the quoted definition of its argument(s).
It is useful for renaming macros, especially built-ins.
.TP
pushdef
like
.IR define ,
but saves any previous definition.
.TP
popdef
removes current definition of its argument(s),
exposing the previous one if any.
.TP
ifdef
if the first argument is defined, the value is the second argument,
otherwise the third.
If there is no third argument, the value is null.
The word
.I unix\^
is predefined on the
.SM UNIX
System versions of
.IR m4 .
.TP
shift
returns all but its first argument.
The other arguments are quoted and pushed back with
commas in between.
The quoting nullifies the effect of the extra scan that
will subsequently be performed.
.TP
changequote
change quote symbols to the first and second arguments.
The symbols may be up to five characters long.
.I Changequote\^
without arguments restores the original values
(i.e., `\|').
.TP
changecom
change left and right comment markers from the default
.B #
and new-line.
With no arguments, the comment mechanism is effectively
disabled.
With one argument, the left marker becomes the argument and
the right marker becomes new-line.
With two arguments, both markers are affected.
Comment markers may be up to five characters long.
.TP
divert
.I m4\^
maintains 10 output streams,
numbered 0-9.
The final output is the concatenation of the streams
in numerical order;
initially stream 0 is the current stream.
The
.I divert\^
macro changes the current output stream to its (digit-string)
argument.
Output diverted to a stream other than 0 through 9
is discarded.
.TP
undivert
causes immediate output of text from diversions named as
arguments, or all diversions if no argument.
Text may be undiverted into another diversion.
Undiverting discards the diverted text.
.TP
divnum
returns the value of the current output stream.
.TP
dnl
reads and discards characters up to and including the next new-line.
.TP
ifelse
has three or more arguments.
If the first argument is the same string as the second,
then the value is the third argument.
If not, and if there are more than four arguments, the process is repeated with arguments 4, 5, 6 and 7.
Otherwise, the value is either the fourth string, or, if it is not present,
null.
.TP
incr
returns the value of its argument incremented by 1.
The value of the argument is calculated
by interpreting an initial digit-string as a decimal number.
.TP
decr
returns the value of its argument decremented by 1.
.TP
eval
evaluates its argument as an arithmetic expression, using 32-bit arithmetic.
Operators include +, \-, \(**, /, %, ^ (exponentiation),
bitwise &, \||\|, ^, and ~ ; relationals; parentheses. 
Octal and hex numbers may be specified as in C.
The second argument specifies the radix for the result;
the default is 10.
The third argument may be used to specify the minimum number
of digits in the result.
.TP
len
returns the number of characters in its argument.
.TP
index
returns the position in its first argument where the second argument begins (zero origin),
or \-1 if the second argument does not occur.
.TP
substr
returns a substring of its first argument.
The second argument is a zero origin
number selecting the first character;
the third argument indicates the length of the substring.
A missing third argument is taken to be large enough to extend to
the end of the first string.
.TP
translit
transliterates the characters in its first argument
from the set given by the second argument to the set given by the third.
No abbreviations are permitted.
.TP
include
returns the contents of the file named in the argument.
.TP
sinclude
is identical to
.IR include ,
except that it
says nothing if the file is inaccessible.
.TP
syscmd
executes the
.SM UNIX
System command given in the first argument.
No value is returned.
.TP
sysval
is the return code from the last call to
.IR syscmd .
.TP
maketemp
fills in a string of
.SM XXXXX
in its argument with the current process
.SM ID\*S.
.TP
m4exit
causes immediate exit from
.IR m4 .
Argument 1, if given, is the exit code;
the default is 0.
.TP
m4wrap
argument 1 will be pushed back at final
.SM EOF\*S;
example: m4wrap(`cleanup(\|)')
.TP
errprint
prints its argument
on the diagnostic output file.
.TP
dumpdef
prints current names and definitions,
for the named items, or for all if no arguments are given.
.TP
traceon
with no arguments, turns on tracing for all macros
(including built-ins).
Otherwise, turns on tracing for named macros.
.TP
traceoff
turns off trace globally and for any macros specified.
Macros specifically traced by
.I traceon\^
can be untraced only by specific calls to
.IR traceoff .
.SH EXAMPLE
.IP
m4 file1 file2 > outputfile
.PP
will run the 
.I m4\^
macro processor on the files "file1" and "file2",
redirecting the output into "outputfile".
.SH SEE ALSO
cc(1),
cpp(1).
.br
.I "The M4 Macro Processor\^"
by B. W. Kernighan and D. M. Ritchie.
.\"	@(#)m4.1	5.1 of 11/8/83
