'\"macro stdmacro
.TH NEWFORM 1
.SH NAME
newform \- change the format of a text file
.SH SYNOPSIS
.B newform
[ options ] files ...
.SH DESCRIPTION
\f2Newform\^\f1 reads lines from the named
.IR files ,
or the standard input if no input file is named,
and reproduces the lines on the standard output.
Lines are reformatted in accordance with
command line options in effect.
.PP
Except for
.BR \-s ,
command line options may appear in any order,
may be repeated, and
may be intermingled with the optional
.IR files .
Command line options are processed in
the order specified.
This means that option sequences like
.RB " \-e 15
.BR \-l 60"
will yield results different from
.RB " \-l 60
.BR \-e 15".
Options are applied to all
.I files\^
on the command line.
.TP "\w'\f3\-o\|\f2tabspec\f1\ \ 'u"
.BI \-i\| tabspec
Input tab specification:
expands tabs to spaces, according to
the tab specifications given.
.I Tabspec\^
recognizes all tab specification forms
described in
.IR tabs\^ (1).
In addition,
.I tabspec\^
may be
.BR \-\- ,
in which
.I newform\^
assumes that the
tab specification is to be
found in the first line read from the
standard input (see
.IR fspec\^ (4)).
If no
.I tabspec\^
is given,
.I tabspec\^
defaults to
.BR \-8 .
A
.I tabspec\^
of
.B \-0
expects no tabs; if any are found, they are treated as
.BR \-1 .
.TP
.BI \-o\| tabspec
Output tab specification:
replaces spaces by tabs, according to the tab specifications given.
The tab specifications are the
same as for
\f3\-i\|\f2tabspec\f1.
If no
.I tabspec\^
is given,
.I tabspec\^
defaults to
.BR \-8 .
A
.I tabspec\^
of
.B \-0
means that no spaces will be converted to tabs on output.
.TP
.BR \-l\| [\f2n\f1]
Set the effective line length to
.I n\^
characters.
If
.I n\^
is not entered,
.B \-l
defaults to 72.
The default line length without the
.B \-l
option is 80 characters.
Note that tabs and backspaces are considered to be one character
(use
.B \-i
to expand tabs to spaces).
.TP
.BR \-b\| [\f2n\f1]
Truncate
.I n\^
characters from the beginning of the line
when the line length is greater than the effective line length
(see
\f3\-l\|\f2[n]\f1).
Default is to truncate
the number of characters necessary
to obtain the effective line length.
The default value is used when
.B \-b
with no
.I n\^
is used.
This option can be used to delete the sequence numbers from a
.SM COBOL
program as follows:
.br
.RS 20
newform\ \|\-l1\ \|\-b7\ \|file-name
.RE
.TP
\&
The
.B \-l1
must be used to set the effective line length shorter than any existing
line in the file so that the
.B \-b
option is activated.
.TP
.BR \-e\| [\f2n\f1]
Same as
.BR \-b\| [\f2n\f1]
except that characters are truncated
from the end of the line.
.TP
.BI \-c\| k
Change the prefix/append character to
.IR k .
Default character for
.I k\^
is a space.
.TP
.BR \-p\| [\f2n\f1]
Prefix
.I n\^
characters (see
\f3\-c\|\f2k\f1)
to the beginning of a
line when the line length is less than the effective
line length.
Default is to prefix the number of characters necessary
to obtain the effective line length.
.TP
.BR \-a\| [\f2n\f1]
Same as 
.BR \-p\| [\f2n\f1]
except characters are
appended to the end of a line.
.TP
.B \-f
Write the tab specification format
line on the standard output before
any other lines are output.
The tab specification format line which is printed
will correspond to the format specified
in the
.I last\^
.B \-o
option.
If no
.B \-o
option is specified, the line which is printed will
contain the default specification of
.BR \-8 .
.TP
.B \-s
Shears off leading characters on each line up to the first tab and
places up to 8 of the sheared characters at the end of the line.
If more than 8 characters (not counting the first tab) are sheared,
the eighth character is replaced by an \(**
and any characters to the right of it are discarded.
The first tab is always discarded.
.TP
\&
An error message and program exit will occur if this option
is used on a file without a tab on each line.
The characters sheared off are saved internally until all other
options specified are applied to that line.
The characters are then added at the end of the processed line.
.TP
\&
For example, to convert a file with leading digits,
one or more tabs, and text on each line, to a file beginning with the
text, all tabs after the first expanded to spaces,
padded with spaces out to column 72 (or truncated to column 72),
and the leading digits placed starting at column 73, the command would be:
.br
.RS 20
newform\ \|\-s\ \|\-i\ \|\-l\ \|\-a\ \|\-e\ \|file-name
.RE
.SH DIAGNOSTICS
.PD 0
All diagnostics are fatal.
.TP "\w'\f2tabspec indirection illegal\f1\ \ \ 'u"
.IR usage: \ \|.\|.\|. 
.I Newform\^
was called with a bad option.
.TP
.I "not \-s format" 
There was no tab on one line.
.TP
.I "can't open file" 
Self explanatory.
.TP
.I "internal line too long" 
A line exceeds 512 characters
after being expanded in the internal work buffer.
.TP
.I "tabspec in error" 
A tab specification is incorrectly formatted,
or specified tab stops are not ascending.
.TP
.I "tabspec indirection illegal" 
A
.I tabspec\^
read from a file (or
standard input) may not contain a
.I tabspec\^
referencing another 
file (or standard input).
.PD
.SH "EXIT CODES"
0 \- normal execution
.br
1 \- for any error
.SH "SEE ALSO"
csplit(1),
tabs(1),
fspec(4).
.SH BUGS
.I Newform\^
normally only keeps track of physical characters;
however,
for the 
.B \-i
and
.B \-o
options,
.I newform\^
will keep track of backspaces in order
to line up tabs in the appropriate logical columns.
.PP
.I Newform\^
will not prompt the user if a
.I tabspec\^
is to be read from the
standard input (by use of 
.B \-i\-\-
or 
.BR \-o\-\- ).
.PP
If the
.B \-f
option is used,
and the last
.B \-o
option specified was
.BR \-o\-\- ,
and was preceded by either a
.B \-o\-\-
or a
.BR \-i\-\- ,
the tab specification format line
will be incorrect.
.\"	@(#)newform.1	5.1 of 11/17/83
