'\"macro stdmacro
.TH NICE 1
.SH NAME
nice \- run a command at low priority
.SH SYNOPSIS
.B nice
[
.BR \- increment
]
command [ arguments ]
.SH DESCRIPTION
.I Nice\^
executes
.I command\^
with a lower
.SM CPU
scheduling priority.
If the
.I increment\^
argument (in the range 1-19) is given,
it is used;
if not, an increment of 10 is assumed.
.PP
The super-user may run commands with
priority higher than normal
by using a negative increment,
e.g.,
.BR \-\-10 .
.SH EXAMPLE
.PP
For the Bourne shell:
.IP
nice -10 date
.PP
would cause the program 
.I date\^
to be processed at a priority lower than normal (0),
i.e., at +10.
In the C shell, the same is achieved by typing in
.IP
nice +10 date
.SH SEE ALSO
nohup(1), nice(2).
.SH DIAGNOSTICS
.I Nice\^
returns the exit status of the subject command.
.SH BUGS
An
.I increment\^
larger than 19 is equivalent to 19.
.\"	@(#)nice.1	5.1 of 11/9/83
