'\"macro stdmacro
.TH PWD 1
.SH NAME
pwd \- working directory name
.SH SYNOPSIS
.B pwd
.SH DESCRIPTION
.I Pwd\^
prints the path name of the working (current) directory.
.SH EXAMPLE
.IP
pwd
.PP
produces a pathname, such as
.BR /usr/games ,
indicating what directory you are currently in.
.SH "SEE ALSO"
cd(1).
.SH DIAGNOSTICS
"Cannot open .." and "Read error in .." indicate
possible file system trouble and should be
referred to a \s-1UNIX\s0 system programming counselor.
.\"	@(#)pwd.1	5.1 of 11/9/83
