'\"macro stdmacro
.TH STRINGS 1
.SH NAME
strings \- find the printable strings in an object, or other binary file
.SH SYNOPSIS
.B strings
[
.B \-
] [
.B \-o
] [
\f3\-\f2number\f1
] file ...
.SH DESCRIPTION
.I Strings\^
looks for ascii strings in a binary file.
A string is any sequence of 4 or more printing characters ending with
a newline or a null.
Unless the
.B \-
flag is given,
.I strings\^
only looks in the initialized data space of object files.
If the
.B \-o
flag is given, then each string is preceded by its offset in the
file (in decimal).
If the
\f3\-\f2number\f1
flag is given, then number is used as the minimum string length
rather than 4.
.PP
.I Strings\^
is useful for identifying random object files and many other things.
.SH EXAMPLE
.IP
strings obj1
.PP
will locate the 
.SM ASCII\*S-character 
strings in the object file
"obj1".
.SH "SEE ALSO"
od(1).
.SH BUGS
The algorithm for identifying strings is extremely primitive. 
.\"	@(#)strings.1	5.1 of 11/16/83
