'\"macro stdmacro
.TH UPTIME 1
.SH NAME
uptime \- show how long system has been up
.SH SYNOPSIS
.B uptime
.SH DESCRIPTION
Uptime prints the current time, the length of time the system has been up,
and the average number of jobs in the run queue over the last 1, 5 and
15 minutes.
It is, essentially, the first line of a
.IR w (1)
command.
.SH FILES
/vmunix	system name list
.SH SEE ALSO
w(1)
.\" @(#)$Header: /d2/3.7/src/man/u_man/man1/RCS/uptime.1,v 1.1 89/03/27 16:51:13 root Exp $
.\" $Log:	uptime.1,v $
Revision 1.1  89/03/27  16:51:13  root
Initial check-in for 3.7

.\" Revision 1.2  85/05/02  18:21:29  robinf
.\" Updates from 2000 Series Workstation Guide
.\" 
.\" Revision 1.1  84/12/14  15:53:15  bob
.\" Initial revision
.\" 
