# $Source: /d2/3.7/src/man/u_man/RCS/Makefile,v $
# @(#)$Revision: 1.1 $
# $Date: 89/03/27 16:43:42 $

all install clean clobber:
	cd man1			; make $@
	cd man2			; make $@
	cd man3			; make $@
	cd man4			; make $@
	cd man5			; make $@
	cd man6			; make $@

man1:	FRC
	cd man1			; make all

man2:	FRC
	cd man2			; make all

man3:	FRC
	cd man3			; make all

man4:	FRC
	cd man4			; make all

man5:	FRC
	cd man5			; make all

man6:	FRC
	cd man6			; make all

FRC:
