#! /bin/sh
# manxargs - xargs the man page source tree
#
# Usage: manxargs xargs_arguments
#
# xargs_arguments are of same form as arguments to xargs
#
# $Revision: 1.1 $
# $Date: 89/03/27 16:39:35 $
#
cd /pubs/irismanpgs
find [ua]_man troff \( -name '*.[1-8]' -o -name '*.[1-8][a-z]' \) -print \
    | xargs "$@"
