'\"macro stdmacro
.TH INTRO 8
.SH NAME
intro \- introduction to system maintenance procedures
.SH DESCRIPTION
This section outlines procedures that will be of interest to
those charged with the task of system maintenance.
Included are discussions on the topics of boot procedures
and recovery from crashes.
.SH BUGS
No manual can take the place of good, solid experience.
.\"	@(#)intro.8	5.1 of 10/15/83
