# $Source: /d2/3.7/src/man/a_man/man8/RCS/Makefile,v $
# @(#)$Revision: 1.1 $
# $Date: 89/03/27 16:23:28 $

M	= a
S	= 8

all clean clobber:

install:
	cp *.$S* $(DEST)/usr/man/$M_man/man$S
	cd $(DEST)/usr/man/$M_man/man$S;chmod 644 *;chgrp bin *;chown bin *

FRC:
