'\"macro stdmacro
.TH INTRO 7
.SH NAME
intro \- introduction to special files
.SH DESCRIPTION
This section describes special files
that refer to specific
hardware
peripherals and
.SM UNIX
System device drivers.
The names of the entries are generally
derived from
names for the hardware,
as opposed to
the names of the special files themselves.
Characteristics of both the hardware device and the
corresponding
.SM UNIX
System device driver are discussed where applicable.
.SH BUGS
While the names of the entries
.I generally\^
refer to
vendor
hardware names, in certain cases
these names are seemingly arbitrary for various
historical reasons.
.\"	@(#)intro.7	5.1 of 10/15/83
